// Generated by gencpp from file imu_yesense_ros/ImuExtended.msg
// DO NOT EDIT!


#ifndef IMU_YESENSE_ROS_MESSAGE_IMUEXTENDED_H
#define IMU_YESENSE_ROS_MESSAGE_IMUEXTENDED_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_yesense_ros
{
template <class ContainerAllocator>
struct ImuExtended_
{
  typedef ImuExtended_<ContainerAllocator> Type;

  ImuExtended_()
    : acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , angular_velocity_roll(0.0)
    , angular_velocity_pitch(0.0)
    , angular_velocity_yaw(0.0)
    , angle_roll(0.0)
    , angle_pitch(0.0)
    , angle_yaw(0.0)  {
    }
  ImuExtended_(const ContainerAllocator& _alloc)
    : acc_x(0.0)
    , acc_y(0.0)
    , acc_z(0.0)
    , angular_velocity_roll(0.0)
    , angular_velocity_pitch(0.0)
    , angular_velocity_yaw(0.0)
    , angle_roll(0.0)
    , angle_pitch(0.0)
    , angle_yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _acc_x_type;
  _acc_x_type acc_x;

   typedef double _acc_y_type;
  _acc_y_type acc_y;

   typedef double _acc_z_type;
  _acc_z_type acc_z;

   typedef double _angular_velocity_roll_type;
  _angular_velocity_roll_type angular_velocity_roll;

   typedef double _angular_velocity_pitch_type;
  _angular_velocity_pitch_type angular_velocity_pitch;

   typedef double _angular_velocity_yaw_type;
  _angular_velocity_yaw_type angular_velocity_yaw;

   typedef double _angle_roll_type;
  _angle_roll_type angle_roll;

   typedef double _angle_pitch_type;
  _angle_pitch_type angle_pitch;

   typedef double _angle_yaw_type;
  _angle_yaw_type angle_yaw;





  typedef boost::shared_ptr< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> const> ConstPtr;

}; // struct ImuExtended_

typedef ::imu_yesense_ros::ImuExtended_<std::allocator<void> > ImuExtended;

typedef boost::shared_ptr< ::imu_yesense_ros::ImuExtended > ImuExtendedPtr;
typedef boost::shared_ptr< ::imu_yesense_ros::ImuExtended const> ImuExtendedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_yesense_ros::ImuExtended_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_yesense_ros::ImuExtended_<ContainerAllocator1> & lhs, const ::imu_yesense_ros::ImuExtended_<ContainerAllocator2> & rhs)
{
  return lhs.acc_x == rhs.acc_x &&
    lhs.acc_y == rhs.acc_y &&
    lhs.acc_z == rhs.acc_z &&
    lhs.angular_velocity_roll == rhs.angular_velocity_roll &&
    lhs.angular_velocity_pitch == rhs.angular_velocity_pitch &&
    lhs.angular_velocity_yaw == rhs.angular_velocity_yaw &&
    lhs.angle_roll == rhs.angle_roll &&
    lhs.angle_pitch == rhs.angle_pitch &&
    lhs.angle_yaw == rhs.angle_yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_yesense_ros::ImuExtended_<ContainerAllocator1> & lhs, const ::imu_yesense_ros::ImuExtended_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_yesense_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2eb288617eb70de805bdc572560b798f";
  }

  static const char* value(const ::imu_yesense_ros::ImuExtended_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2eb288617eb70de8ULL;
  static const uint64_t static_value2 = 0x05bdc572560b798fULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_yesense_ros/ImuExtended";
  }

  static const char* value(const ::imu_yesense_ros::ImuExtended_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 acc_x\n"
"float64 acc_y\n"
"float64 acc_z\n"
"float64 angular_velocity_roll\n"
"float64 angular_velocity_pitch\n"
"float64 angular_velocity_yaw\n"
"float64 angle_roll\n"
"float64 angle_pitch\n"
"float64 angle_yaw\n"
;
  }

  static const char* value(const ::imu_yesense_ros::ImuExtended_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acc_x);
      stream.next(m.acc_y);
      stream.next(m.acc_z);
      stream.next(m.angular_velocity_roll);
      stream.next(m.angular_velocity_pitch);
      stream.next(m.angular_velocity_yaw);
      stream.next(m.angle_roll);
      stream.next(m.angle_pitch);
      stream.next(m.angle_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuExtended_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_yesense_ros::ImuExtended_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_yesense_ros::ImuExtended_<ContainerAllocator>& v)
  {
    s << indent << "acc_x: ";
    Printer<double>::stream(s, indent + "  ", v.acc_x);
    s << indent << "acc_y: ";
    Printer<double>::stream(s, indent + "  ", v.acc_y);
    s << indent << "acc_z: ";
    Printer<double>::stream(s, indent + "  ", v.acc_z);
    s << indent << "angular_velocity_roll: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity_roll);
    s << indent << "angular_velocity_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity_pitch);
    s << indent << "angular_velocity_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.angular_velocity_yaw);
    s << indent << "angle_roll: ";
    Printer<double>::stream(s, indent + "  ", v.angle_roll);
    s << indent << "angle_pitch: ";
    Printer<double>::stream(s, indent + "  ", v.angle_pitch);
    s << indent << "angle_yaw: ";
    Printer<double>::stream(s, indent + "  ", v.angle_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_YESENSE_ROS_MESSAGE_IMUEXTENDED_H
