# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu_yesense_ros/ImuExtended.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ImuExtended(genpy.Message):
  _md5sum = "2eb288617eb70de805bdc572560b798f"
  _type = "imu_yesense_ros/ImuExtended"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 acc_x
float64 acc_y
float64 acc_z
float64 angular_velocity_roll
float64 angular_velocity_pitch
float64 angular_velocity_yaw
float64 angle_roll
float64 angle_pitch
float64 angle_yaw
"""
  __slots__ = ['acc_x','acc_y','acc_z','angular_velocity_roll','angular_velocity_pitch','angular_velocity_yaw','angle_roll','angle_pitch','angle_yaw']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       acc_x,acc_y,acc_z,angular_velocity_roll,angular_velocity_pitch,angular_velocity_yaw,angle_roll,angle_pitch,angle_yaw

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ImuExtended, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.acc_x is None:
        self.acc_x = 0.
      if self.acc_y is None:
        self.acc_y = 0.
      if self.acc_z is None:
        self.acc_z = 0.
      if self.angular_velocity_roll is None:
        self.angular_velocity_roll = 0.
      if self.angular_velocity_pitch is None:
        self.angular_velocity_pitch = 0.
      if self.angular_velocity_yaw is None:
        self.angular_velocity_yaw = 0.
      if self.angle_roll is None:
        self.angle_roll = 0.
      if self.angle_pitch is None:
        self.angle_pitch = 0.
      if self.angle_yaw is None:
        self.angle_yaw = 0.
    else:
      self.acc_x = 0.
      self.acc_y = 0.
      self.acc_z = 0.
      self.angular_velocity_roll = 0.
      self.angular_velocity_pitch = 0.
      self.angular_velocity_yaw = 0.
      self.angle_roll = 0.
      self.angle_pitch = 0.
      self.angle_yaw = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.angular_velocity_roll, _x.angular_velocity_pitch, _x.angular_velocity_yaw, _x.angle_roll, _x.angle_pitch, _x.angle_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.angular_velocity_roll, _x.angular_velocity_pitch, _x.angular_velocity_yaw, _x.angle_roll, _x.angle_pitch, _x.angle_yaw,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_9d().pack(_x.acc_x, _x.acc_y, _x.acc_z, _x.angular_velocity_roll, _x.angular_velocity_pitch, _x.angular_velocity_yaw, _x.angle_roll, _x.angle_pitch, _x.angle_yaw))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 72
      (_x.acc_x, _x.acc_y, _x.acc_z, _x.angular_velocity_roll, _x.angular_velocity_pitch, _x.angular_velocity_yaw, _x.angle_roll, _x.angle_pitch, _x.angle_yaw,) = _get_struct_9d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_9d = None
def _get_struct_9d():
    global _struct_9d
    if _struct_9d is None:
        _struct_9d = struct.Struct("<9d")
    return _struct_9d
